# .github/workflows/ci.yml
name: CI & CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout & Python/UV setup
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install uv
      - run: uv sync

      # 2) Run your unit tests
      - run: uv run pytest --maxfail=1 --disable-warnings -q

      # 3) Authenticate & configure gcloud (incl. Cloud Build + GCR)
      - name: Authenticate & configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id:          ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 4) Build & push your container via Cloud Build → GCR
      - name: Build & push to GCR
        run: |
          gcloud builds submit . \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/penguin-ml:end2end

      # 5) Deploy that image to Cloud Run (managed)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy penguin-ml \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/penguin-ml:end2end \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
