name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install UV
      run: pip install uv

    - name: Sync environment
      run: uv sync

    - name: Run tests
      run: uv run pytest --maxfail=1 --disable-warnings -q

    - name: Build Docker image
      run: docker build -t penguin-ml:end2end .

          # This part is for pushing the Docker image to Docker Hub

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/penguin-ml:end2end
        docker tag penguin-ml:end2end "$IMAGE_NAME"
        docker push "$IMAGE_NAME"
