# .github/workflows/ci.yml
name: CI & CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Setup Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3) Install UV & sync dependencies
      - name: Install UV CLI
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      # 4) Run tests
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      # 5) Build Docker image
      - name: Build Docker image
        run: docker build -t anasriad8/penguin-ml:end2end .

      # 6) Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag anasriad8/penguin-ml:end2end anasriad8/penguin-ml:${{ github.sha }}
          docker push anasriad8/penguin-ml:end2end
          docker push anasriad8/penguin-ml:${{ github.sha }}

      # 7) Authenticate to GCP with service account key
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 8) Set active GCP project
      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # 9) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy penguin-ml \
            --image docker.io/anasriad8/penguin-ml:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
