# .github/workflows/ci.yml
name: CI & CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python & UV
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV CLI
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      # 3) Run your unit tests
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      # 4) Authenticate to GCP using your service-account JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          # this is the only key this action accepts:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5) Install gcloud, select project, export creds
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id:        ${{ secrets.GCP_PROJECT_ID }}


      # 6) Deploy that image to Cloud Run (managed)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy penguin-ml \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/penguin-ml:end2end \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
