# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) grab your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) get Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3) install your CLI helper and sync your UV environment
      - name: Install UV CLI
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      # 4) unit tests
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      # 5) build your container
      - name: Build Docker image
        run: docker build -t anasriad8/penguin-ml:end2end .

      # 6) push it up to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag anasriad8/penguin-ml:end2end \
                     anasriad8/penguin-ml:${{ github.sha }}
          docker push anasriad8/penguin-ml:end2end
          docker push anasriad8/penguin-ml:${{ github.sha }}
