name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install UV CLI
        run: pip install uv-cli

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      # ─── New: Train & log to MLflow ───────────────────────────
      - name: Install MLflow
        run: pip install mlflow

      - name: Train model and log to MLflow
        run: |
          python -m src.train \
            --mlflow-tracking-uri http://localhost:5001 \
            --experiment-name penguins

      - id: get_run
        name: Fetch latest MLflow run ID
        run: |
          python - <<EOF
import mlflow
client = mlflow.tracking.MlflowClient("http://localhost:5001")
runs = client.search_runs("0",
    order_by=["attributes.start_time DESC"],
    max_results=1
)
run_id = runs[0].info.run_id
print(f"::set-output name=RUN_ID::{run_id}")
EOF

      - name: Download model artifact
        run: |
          mlflow artifacts download \
            --run-id ${{ steps.get_run.outputs.RUN_ID }} \
            --artifact-path rf_model/model.pkl \
            -o src/models/model.pkl

      # ─── Build & Push Docker Image ────────────────────────────
      - name: Build Docker image
        run: docker build -t anasriad8/penguin-ml:end2end .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag anasriad8/penguin-ml:end2end \
                     anasriad8/penguin-ml:${{ github.sha }}
          docker push anasriad8/penguin-ml:end2end
          docker push anasriad8/penguin-ml:${{ github.sha }}
